### ISSUE TITLE
Meteor 1.2

### ISSUE THREAD

**Issue by jjeffwarner** [poetic/meteor-materialize-sass#11]
I upgraded my project to Meteor 1.2 and ran into an issue with the files in .meteor/local/build/programs/server/assets/packages/poetic_materialize-scss/bower_components/materialize/sass/components/ no longer existing. A meteor reset and running meteor did not rebuild them either.

**Comment by appinteractive** [comment]
Cross Meteor Imports should be used, there is a ticket on the fourseven scss compiler: https://github.com/fourseven/meteor-scss/issues/106. Does this package have to adopt it either?

**Comment by Chun-Yang** [comment]
Thank you @appinteractive , I will update this package whenever https://github.com/fourseven/meteor-scss/issues/106 is resolved.

**Comment by boustanihani** [comment]
I am getting:

```
While building the application:

/<my-project>/client/stylesheets/index.scss:41:9:
Scss compiler error: file to import not found or unreadable:
.meteor/local/build/programs/server/assets/packages/poetic_materialize-scss/bower_components/materialize/sass/materialize.scss
Current dir: /<my-project>/client/stylesheets/
```

Is it realted to this bug (**Cross Meteor Imports**) ?

**Comment by jjeffwarner** [comment]
@boustanihani If it was working before Meteor 1.2 then yes. With the new version the bower_components/... files are not building.

**Comment by boustanihani** [comment]
I managed to start my server (`meteor run`) by copying the files manually but I can't find a workaround for `meteor build` ... hope this gets fixed soon.

**Comment by jjeffwarner** [comment]
Revert to previous version of Meteor. git revert HEAD saved my bacon.

**Comment by sean-stanley** [comment]
fourseven/meteor-scss#106 issue is closed. Does this package still need updates? I have the same issue.

**Comment by jjeffwarner** [comment]
Fixing the #106 issue helped some but the it looks like the autoprefixer is stopping it from working now. The component files are being built correctly in the .meteor directory now but the @import lines with relative files do not work.

**Comment by TomFreudenberg** [comment]
Hi @Chun-Yang , do you have any idea to this? It currently stops my app from build. I tried once the import via a full-path for @import statement but then it stops with relative files. 

Thanks for some smart hint.

**Comment by TomFreudenberg** [comment]
Hmm .. maybe it is still an error from fourseven.

What I did to test:

`cd client/stylesheets` # all my scss starting there

change @import to

`../../.meteor/local/build/programs/server/assets/packages/poetic_materialize-scss/bower_components/materialize/sass/materialize.scss`

relative to my folder structure

`npm install -g node-sass` # if not already available

change the filename of index so that meteor does not take care

`mv index.scss index.scss.txt`

and then build my css once manually

`node-sass index.scss.txt my_theme.css`

after that launching meteor

`meteor`

---

from my point of view the call of `node-sass` / `sass.render()` isn't correct yet even in the latest release 3.3.3_1 of materialize-scss

**Comment by Chun-Yang** [comment]
Following https://github.com/englue/meteor-bootstrap3-sass/commit/26ca6b8a5f770fc32b9640d15ae15641b4a571cd I will update this package shortly.

**Comment by TomFreudenberg** [comment]
I send you a PR and here is my commit that fixes that on my systems

https://github.com/poetic/meteor-materialize-sass/commit/8e448c430c0dd5d85f56dbed8b82d11a9351261f

Cheers
Tom

**Comment by Chun-Yang** [comment]
Hey @TomFreudenberg , thank you for your update. However I already did the same thing. Right now the package is working on master branch. 

Due to my bad internet connection I can not push to meteor successfully. 

Whoever want to update to Meteor@1.2 can clone this repo. Later on I will publish it to meteor.

**Comment by TomFreudenberg** [comment]
Great, maybe you like also my suggestion to change path name "bower_components" to more general "assets" as I guess this is the meteor way?

**Comment by Chun-Yang** [comment]
Actually the 'bower_component' folder is convenient for us to update materialize version. With that folder we can use bower to help us manage versions.

**Comment by TomFreudenberg** [comment]
ok, that's a point 

I drop my repo now - thanks for your updates

**Comment by Chun-Yang** [comment]
Just updated to 1.3.3. Please try this new build. Thank you all for your support.

**Comment by TomFreudenberg** [comment]
Hi @Chun-Yang 

thanks for your work, can confirm working new release!

**Comment by jjeffwarner** [comment]
Thank you as well!

Jeff
