### ISSUE TITLE
Use bower_components/materialize as a git submodule?

### ISSUE THREAD

**Issue by mitar** [poetic/meteor-materialize-sass#17]
I think bower_components/materialize should be a git submodule (even if it is a fork). Then it will be easier to understand what changes were made to the codebase and easier to merge upstream changes.

**Comment by Chun-Yang** [comment]
Thank you for your suggestion. From my understanding, there is no git history in a package installed by bower. And almost all the important changes happens in the bower_components folder. The git history already is a reflection of the changes in all the files including bower_components. A submodule does not bring a lot of value to our repo management.

Please tell me if I miss anything.

**Comment by mitar** [comment]
Hmm, not sure why are you using bower to begin with? Or why you do not have it configured to use materialize from a git submodule in the same repository?

**Comment by Chun-Yang** [comment]
Oh I get it now. I agree that I should have used their git repo in the beginning. I will use the git submodule in the future. 

The bower solution was attractive in the beginning because:
1. I thought I would not need to change the source code of that repo.
2. The bower package is much smaller than the whole source code. 

Thank you, I will use git submodule in the next update.

**Comment by Chun-Yang** [comment]
Please check the new repo: https://github.com/poetic/meteor-materialize-scss
